// This file is auto-generated. Do not edit manually.
// Run: bun run sync-skill-ids

export const SKILL_IDS = [
  "adobe-illustrator",
  "adobe-photoshop",
  "affinity-photo",
  "ai-agentic-code-reviews",
  "ai-agentic-development",
  "angular-1",
  "auth0",
  "aws",
  "aws-cognito",
  "babel",
  "bun",
  "capn-proto",
  "cloudflare",
  "convex",
  "css",
  "cypress",
  "datadog",
  "design-consulting",
  "design-systems",
  "diagramming",
  "docker",
  "docusaurus",
  "e2e-testing",
  "electron",
  "feature-flags",
  "figma",
  "git",
  "github",
  "github-actions",
  "html",
  "javascript",
  "jquery",
  "launchdarkly",
  "msw",
  "napkin-sketching",
  "netlify",
  "netlify-functions",
  "next-js-apis",
  "node-js",
  "pdf-creation",
  "php",
  "postgresql",
  "product-discovery",
  "project-management",
  "rapid-prototyping",
  "react",
  "rest-apis",
  "rpc",
  "sdlc",
  "sketch-app",
  "tailwind",
  "tanstack-query",
  "tanstack-start",
  "turborepo",
  "typescript",
  "unit-testing",
  "vercel",
  "visual-design",
  "vite",
  "vue-2",
  "vue-3",
  "webpack",
  "wordpress",
] as const;

export type SkillId = (typeof SKILL_IDS)[number];
