// This file is auto-generated. Do not edit manually.
// Run: bun run sync-skill-ids

export const SKILL_IDS = [
  "affinity-photo",
  "ai-agentic-code-reviews",
  "ai-agentic-development",
  "angular-1",
  "aws",
  "aws-cognito",
  "babel",
  "bun",
  "capn-proto",
  "cloudflare",
  "convex",
  "cypress",
  "datadog",
  "design-consulting",
  "design-systems",
  "diagramming",
  "docusaurus",
  "e2e-testing",
  "feature-flags",
  "figma",
  "git",
  "github",
  "github-actions",
  "html-css",
  "illustrator",
  "javascript",
  "jquery",
  "napkin-sketching",
  "netlify",
  "next-js-apis",
  "node-js",
  "pdf-creation",
  "photoshop",
  "php",
  "postgresql",
  "product-discovery",
  "project-management",
  "rapid-prototyping",
  "react",
  "react-17",
  "rest-apis",
  "sdlc",
  "tailwind",
  "tanstack-query",
  "turborepo",
  "typescript",
  "unit-testing",
  "vercel",
  "visual-design",
  "vite",
  "vue-2",
  "vue-3",
  "webpack",
  "wordpress",
] as const;

export type SkillId = (typeof SKILL_IDS)[number];
